sudo: required

services:
    - docker

before_install:
    - docker build -t coupdevent/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true coupdevent/docker-react npm run test -- --coverage     